In [1]:
## import required packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings(action='ignore')

# UDF
from function import metrices_calculation

In [2]:
df = pd.read_csv('Employee-Attrition.csv')
df.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 35 columns]

### columns to be dropped
    'EmployeeNumber' => this is nominal data 
    'StandardHours' => zero variance
    'EmployeeCount'=> zero variance
    'DailyRate', 'HourlyRate' & 'MonthlyRate' should be correlated (further analysis required)
    'Over18' => zero variance

In [3]:
# dropping columns
df.drop(['StandardHours','EmployeeCount','Over18'], axis = 1, inplace = True)

In [4]:
df['Attrition'] = df.Attrition.map({'Yes':1,'No':0})
df = pd.get_dummies(df) ## OHE encoding

In [5]:
df.shape

(1470, 53)

In [6]:
df.head()

Age  Attrition  DailyRate  DistanceFromHome  Education  EmployeeNumber  \
0   41          1       1102                 1          2               1   
1   49          0        279                 8          1               2   
2   37          1       1373                 2          2               4   
3   33          0       1392                 3          4               5   
4   27          0        591                 2          1               7   

   EnvironmentSatisfaction  HourlyRate  JobInvolvement  JobLevel  ...  \
0                        2          94               3         2  ...   
1                        3          61               2         2  ...   
2                        4          92               2         1  ...   
3                        4          56               3         1  ...   
4                        1          40               3         1  ...   

   JobRole_Manufacturing Director  JobRole_Research Director  \
0                               0                          0   
1                               0                          0   
2                               0                          0   
3                               0                          0   
4                               0                          0   

   JobRole_Research Scientist  JobRole_Sales Executive  \
0                           0                        1   
1                           1                        0   
2                           0                        0   
3                           1                        0   
4                           0                        0   

   JobRole_Sales Representative  MaritalStatus_Divorced  \
0                             0                       0   
1                             0                       0   
2                             0                       0   
3                             0                       0   
4                             0                       0   

   MaritalStatus_Married  MaritalStatus_Single  OverTime_No  OverTime_Yes  
0                      0                     1            0             1  
1                      1                     0            1             0  
2                      0                     1            0             1  
3                      1                     0            0             1  
4                      1                     0            1             0  

[5 rows x 53 columns]

In [7]:
## import sklearn functions
from sklearn.linear_model import LogisticRegressionCV, LogisticRegression, RidgeClassifierCV,RidgeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score, cross_val_predict
from sklearn.preprocessing import StandardScaler, Normalizer
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

In [8]:
### data splitting into features & target
X = df.drop(['EmployeeNumber','Attrition'], axis = 1)
y = df.Attrition

In [9]:
X.head()

Age  DailyRate  DistanceFromHome  Education  EnvironmentSatisfaction  \
0   41       1102                 1          2                        2   
1   49        279                 8          1                        3   
2   37       1373                 2          2                        4   
3   33       1392                 3          4                        4   
4   27        591                 2          1                        1   

   HourlyRate  JobInvolvement  JobLevel  JobSatisfaction  MonthlyIncome  ...  \
0          94               3         2                4           5993  ...   
1          61               2         2                2           5130  ...   
2          92               2         1                3           2090  ...   
3          56               3         1                3           2909  ...   
4          40               3         1                2           3468  ...   

   JobRole_Manufacturing Director  JobRole_Research Director  \
0                               0                          0   
1                               0                          0   
2                               0                          0   
3                               0                          0   
4                               0                          0   

   JobRole_Research Scientist  JobRole_Sales Executive  \
0                           0                        1   
1                           1                        0   
2                           0                        0   
3                           1                        0   
4                           0                        0   

   JobRole_Sales Representative  MaritalStatus_Divorced  \
0                             0                       0   
1                             0                       0   
2                             0                       0   
3                             0                       0   
4                             0                       0   

   MaritalStatus_Married  MaritalStatus_Single  OverTime_No  OverTime_Yes  
0                      0                     1            0             1  
1                      1                     0            1             0  
2                      0                     1            0             1  
3                      1                     0            0             1  
4                      1                     0            1             0  

[5 rows x 51 columns]

In [10]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Attrition, dtype: int64

### 
1. Why scaling is important?
2. Is scaling important always?
3. should it be done on features or target or both?

In [11]:
## scaling data
scaler = StandardScaler()
scaler.fit(X, y)
X_ = scaler.transform(X)

In [12]:
print(X_[:2])

[[ 0.4463504   0.74252653 -1.01090934 -0.89168825 -0.66053067  1.38313827
   0.37967213 -0.05778755  1.15325359 -0.10834951  0.72601994  2.12513592
  -1.1505541  -0.42623002 -1.58417824 -0.93201439 -0.42164246 -2.17198183
  -2.49382042 -0.16461311 -0.0632959  -0.67914568  0.24583399 -0.33709993
  -0.48185865  0.63984058 -0.21160368 -1.37405084  1.51524392 -0.13678823
   1.19404463 -0.34825488 -0.67914108 -0.24305927 -0.31409347  1.22474487
  -1.22474487 -0.3127846  -0.1914977  -0.46246387 -0.27305934 -0.33080804
  -0.23990406 -0.49787324  1.87328654 -0.24462499 -0.53487311 -0.91892141
   1.45864991 -1.59174553  1.59174553]
 [ 1.32236521 -1.2977746  -0.14714972 -1.86842575  0.25462493 -0.24067677
  -1.02616674 -0.05778755 -0.66085318 -0.29171859  1.48887614 -0.67804939
   2.12930601  2.34615106  1.19143799  0.24198831 -0.1645114   0.15570708
   0.33809616  0.48850773  0.76499762 -0.36871529  0.80654148 -0.33709993
   2.07529738 -1.5628893  -0.21160368  0.72777511 -0.65995975 -0.13678823

In [13]:
### splitting data into train and validation/test sets by 80:20 ratio
X_train, X_test, y_train, y_test = train_test_split(X_,y,test_size = 0.2, stratify = y, random_state = 42)
print(X_train.shape,y_train.shape )
print(X_test.shape,y_test.shape)

(1176, 51) (1176,)
(294, 51) (294,)


In [14]:
### K-fold cross validation
# 100, K=5
# S1 S2 S3 S4 S5
# 20 20 20 20 20

# 1st iter: S1-> validation set: [S2:S5]-> training set => Accuracy1 = 50
# 2nd iter: S2-> validation set: [Rem]-> training set => A2 = 90
# 3rd iter: S3-> validation set: [Rem]-> training set => A3 = 89
# ...
# 5th iter: S5-> validation set: [Rem]-> training set => A5 = 78

In [15]:
# #### limitations of deep layer
#      - pre-requisite of large dataset 
    
    
# 1. simplity (model complexity is less) 
#  - Linear/Logistic regression (pros:simple model, works well on less data ;cons: starts to perform well with high number of categorical/non-linear data, fails with outliers)
#  - Tree based models(CART, RandomForest/(GradientBoosting/XgBoost)) (Pros:works with non-linearity date,works with outliers ;cons: overfitting,highly instable)
#  - SVM (Pros:can work on mix/inseperable/non-linear/linear data; Drawbacks: computationally expensive)
#  - KNN 
#  - NaiveBased 
#  - DL (Pros: Gives highest accuracy, works with unstructure data; cons: pre-requisite of large dataset )       

In [16]:
# ### features: 10
# 10=> LR: 78; RF: 80
# 9=>  LR: 77; RF: 80 +- large_change   (78)      

In [17]:
# prunning 
# l3: 6+5+2 = 13 

In [18]:
### How to judge our accuracy??

In [19]:
model_estimators = [LogisticRegression, RidgeClassifier, RandomForestClassifier, GradientBoostingClassifier, SVC]
model_names = ['LogisticRegression','RidgeClassifier', 'RandomForest','GradientBoosting','SVC']

In [20]:
### 
def model(est, name, trainX, trainy):
    scores = cross_val_score(estimator = est(), X = trainX, y = trainy, scoring = 'accuracy', cv = 5, n_jobs  = -1)
    print(scores)
    print('{}: Average scores: {}, standard deviation: {}'.format(name, round(np.mean(scores),5),round(np.std(scores),5)))
    

In [21]:
for n,m in zip(model_names, model_estimators):
    model(m,n, X_train,y_train)

[0.86016949 0.88085106 0.89361702 0.88510638 0.89361702]
LogisticRegression: Average scores: 0.88267, standard deviation: 0.01229
[0.86016949 0.86382979 0.87234043 0.86382979 0.87234043]
RidgeClassifier: Average scores: 0.8665, standard deviation: 0.00495
[0.84745763 0.85957447 0.85106383 0.84680851 0.84255319]
RandomForest: Average scores: 0.84949, standard deviation: 0.00572
[0.84322034 0.88510638 0.86382979 0.88085106 0.84680851]
GradientBoosting: Average scores: 0.86396, standard deviation: 0.01707
[0.86016949 0.85957447 0.86808511 0.85957447 0.87659574]
SVC: Average scores: 0.8648, standard deviation: 0.00672


In [22]:
# High average score|least standard deviation

In [23]:
### 
def model_(est, name, trainX, trainy, testX, testy):
    model_ = est().fit(trainX,trainy) 
    ypred_train = model_.predict(trainX)
    ypred_test = model_.predict(testX)
#     precision, recall, fscore, = precision_recall_fscore_support(trainy, ypred_train)
    print('{}:'.format(name))
    print('Train: precision={} recall={}, Test: precision={} recall={}'.format(round(precision_score(trainy, ypred_train)*100,3),
                                                                                 round(recall_score(trainy, ypred_train)*100,3),
                                                                                  round(precision_score(testy, ypred_test)*100,3),
                                                                                  round(recall_score(testy, ypred_test)*100,3)))
          
    

In [24]:
for n,m in  zip(model_names, model_estimators):
    model_(m,n, X_train,y_train,X_test,y_test )

LogisticRegression:
Train: precision=80.672 recall=50.526, Test: precision=61.538 recall=34.043
RidgeClassifier:
Train: precision=88.0 recall=23.158, Test: precision=76.923 recall=21.277
RandomForest:
Train: precision=100.0 recall=92.105, Test: precision=60.0 recall=12.766
GradientBoosting:
Train: precision=100.0 recall=75.263, Test: precision=71.429 recall=21.277
SVC:
Train: precision=98.901 recall=47.368, Test: precision=90.909 recall=21.277


<!-- ![](attachment:image.png) -->
#### precision,recall
<img src='screenshot.jpg' style="width:500px;height:350px" />

In [25]:
#### GridSearchCV is used for hyper-parameters tunning

In [26]:
RandomForestClassifier()

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators='warn',
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

#### hyper-parameters of random forest model are: n_estimators,max_depth,min_samples_split,max_leaf_nodes,max_features


In [27]:
## model to used (assumed)
model_rf = RandomForestClassifier(oob_score=True, random_state=42, min_samples_split = 5,)

## parameters to be tunned
params = {'n_estimators':range(100,200,5),
         'max_depth':range(2,5,1)}
gs = GridSearchCV(estimator=model_rf, param_grid=params,scoring='accuracy', n_jobs=-1, cv = 3)
gs.fit(X_train, y_train)
tunned_results = pd.DataFrame(gs.cv_results_).sort_values(by = 'mean_test_score', ascending = False )

In [28]:
tunned_results

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
53       0.647679      0.007693         0.035699        0.000845   
40       0.515715      0.002814         0.029017        0.008964   
41       0.548190      0.008097         0.028707        0.004075   
59       0.584877      0.048149         0.024595        0.004549   
58       0.686763      0.023959         0.025776        0.002429   
57       0.728501      0.006968         0.041871        0.004815   
56       0.738983      0.009331         0.038997        0.001279   
55       0.728248      0.005535         0.034139        0.001668   
54       0.682058      0.011955         0.044300        0.004203   
52       0.638329      0.004041         0.032770        0.001054   
51       0.718402      0.066101         0.039592        0.003099   
50       0.672819      0.008151         0.032178        0.001719   
49       0.613693      0.034115         0.040687        0.011598   
42       0.569061      0.001597         0.027408        0.001023   
43       0.570288      0.006449         0.030221        0.006991   
44       0.611017      0.008657         0.032303        0.005565   
46       0.573195      0.016510         0.035255        0.006466   
45       0.590426      0.016804         0.025634        0.000369   
47       0.548821      0.002740         0.027795        0.000524   
48       0.561919      0.010610         0.028817        0.000438   
39       0.985333      0.021052         0.062910        0.007042   
37       0.803894      0.032197         0.052669        0.004238   
29       0.676255      0.024352         0.037698        0.008026   
38       0.895770      0.021849         0.054119        0.003824   
36       0.813290      0.026158         0.041385        0.000847   
35       0.881141      0.009037         0.035714        0.001037   
34       0.817647      0.026474         0.054569        0.004125   
33       0.741319      0.017313         0.055738        0.005558   
32       0.765410      0.032117         0.038236        0.003120   
30       0.693031      0.006359         0.048510        0.007111   
28       0.737681      0.007505         0.032849        0.005995   
20       0.451795      0.014100         0.037603        0.004632   
27       0.732498      0.006156         0.043210        0.004221   
26       0.675909      0.037210         0.038615        0.005234   
25       0.574679      0.038936         0.041090        0.002873   
24       0.485559      0.018002         0.044517        0.011343   
23       0.475343      0.008945         0.023803        0.000170   
21       0.519756      0.018615         0.024948        0.004998   
31       0.764568      0.008809         0.039697        0.005352   
22       0.492633      0.009529         0.022558        0.000505   
19       0.837243      0.021029         0.057989        0.003423   
18       0.700645      0.043154         0.044503        0.009915   
17       0.674378      0.005212         0.037736        0.002634   
4        0.406237      0.004815         0.023467        0.001469   
6        0.450407      0.004226         0.026142        0.003216   
5        0.423981      0.004250         0.024685        0.000241   
1        0.369163      0.003064         0.019494        0.000327   
3        0.388954      0.005041         0.022263        0.000409   
2        0.379913      0.001119         0.021496        0.000866   
8        0.475277      0.007488         0.028057        0.001532   
7        0.463305      0.002120         0.026674        0.000502   
15       0.602254      0.017227         0.040391        0.008519   
9        0.492680      0.005312         0.030685        0.003538   
10       0.545989      0.020664         0.033977        0.005305   
11       0.576678      0.003469         0.029915        0.000648   
12       0.583368      0.011930         0.031832        0.000641   
13       0.566955      0.015897         0.032895        0.000253   
14       0.574068      0.004014         0.033440        0.00

In [29]:
# gs.best_estimator_ # returns estimators with best parameters sets
# gs.best_params_  # displays best parameters values
# gs.best_score_ # display best score as per scoring parameter in GridSearchCV

#### All the above steps can be pipelined to excute in sequence once the model is decided by using PipeLine

In [30]:
from sklearn.pipeline import Pipeline

In [31]:
pipline = Pipeline(steps = [('scaler',StandardScaler()),
                 ('model',RandomForestClassifier())])
pipline.fit(X_train, y_train)
pred_tr = pipline.predict(X_train)
pred_te = pipline.predict(X_test)

In [32]:
## train metrics
metrices_calculation(y_train, pred_tr)

print('\n')

## test metrics
metrices_calculation(y_test, pred_te)

Accuracy:0.9787414965986394
 precision:1.0
 recall:0.868421052631579
 confusion matrix:[[986   0]
 [ 25 165]]


Accuracy:0.8401360544217688
 precision:0.5
 recall:0.1702127659574468
 confusion matrix:[[239   8]
 [ 39   8]]


In [33]:
pipline = Pipeline(steps = [('scaler',Normalizer()),
                 ('model',RandomForestClassifier())])
pipline.fit(X_train, y_train)
pred_tr = pipline.predict(X_train)
pred_te = pipline.predict(X_test)

In [34]:
## train metrics
metrices_calculation(y_train, pred_tr)

print('\n')

## test metrics
metrices_calculation(y_test, pred_te)

Accuracy:0.9812925170068028
 precision:1.0
 recall:0.8842105263157894
 confusion matrix:[[986   0]
 [ 22 168]]


Accuracy:0.8435374149659864
 precision:0.5384615384615384
 recall:0.14893617021276595
 confusion matrix:[[241   6]
 [ 40   7]]


In [35]:
pipline = Pipeline(steps = [('scaler',Normalizer()),
                 ('model',LogisticRegression())])
pipline.fit(X_train, y_train)
pred_tr = pipline.predict(X_train)
pred_te = pipline.predict(X_test)

In [36]:
## train metrics
metrices_calculation(y_train, pred_tr)

print('\n')

## test metrics
metrices_calculation(y_test, pred_te)

Accuracy:0.8826530612244898
 precision:0.8939393939393939
 recall:0.3105263157894737
 confusion matrix:[[979   7]
 [131  59]]


Accuracy:0.8707482993197279
 precision:0.7647058823529411
 recall:0.2765957446808511
 confusion matrix:[[243   4]
 [ 34  13]]


In [37]:
pipline = Pipeline(steps = [('scaler',Normalizer()),
                 ('model',RidgeClassifier())])
pipline.fit(X_train, y_train)
pred_tr = pipline.predict(X_train)
pred_te = pipline.predict(X_test)

In [38]:
## train metrics
metrices_calculation(y_train, pred_tr)

print('\n')

## test metrics
metrices_calculation(y_test, pred_te)

Accuracy:0.8690476190476191
 precision:0.9285714285714286
 recall:0.20526315789473684
 confusion matrix:[[983   3]
 [151  39]]


Accuracy:0.8707482993197279
 precision:0.9090909090909091
 recall:0.2127659574468085
 confusion matrix:[[246   1]
 [ 37  10]]
